/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Blank: typeof import('./src/components/blank.vue')['default']
    CloseBtn: typeof import('./src/components/closeBtn.vue')['default']
    DongtaiList: typeof import('./src/components/common/dongtaiList.vue')['default']
    GonglueList: typeof import('./src/components/common/gonglueList.vue')['default']
    HomeBanner_bwg: typeof import('./src/components/homeBanner/homeBanner_bwg.vue')['default']
    HomeBanner_default: typeof import('./src/components/homeBanner/homeBanner_default.vue')['default']
    HomeBanner_dianya: typeof import('./src/components/homeBanner/homeBanner_dianya.vue')['default']
    HomeBanner_guyun: typeof import('./src/components/homeBanner/homeBanner_guyun.vue')['default']
    HomeBlocks_default: typeof import('./src/components/homeBlocks/homeBlocks_default.vue')['default']
    HomeBlocks_guyun: typeof import('./src/components/homeBlocks/homeBlocks_guyun.vue')['default']
    HomeButton_contracted: typeof import('./src/components/homeButton/homeButton_contracted.vue')['default']
    HomeButton_dianya: typeof import('./src/components/homeButton/homeButton_dianya.vue')['default']
    HomeRolling: typeof import('./src/components/common/homeRolling.vue')['default']
    HomeRolling_default: typeof import('./src/components/homeRolling/homeRolling_default.vue')['default']
    HomeTabList_default: typeof import('./src/components/homeTabList/homeTabList_default.vue')['default']
    HomeVR_default: typeof import('./src/components/homeVR/homeVR_default.vue')['default']
    HotList: typeof import('./src/components/common/hotList.vue')['default']
    LanguageToggle_default: typeof import('./src/components/languageToggle/languageToggle_default.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    LuchAudio: typeof import('./src/components/luch-audio.vue')['default']
    MpHtml: typeof import('./src/components/mp-html/mp-html.vue')['default']
    Node: typeof import('./src/components/mp-html/node/node.vue')['default']
    PathList: typeof import('./src/components/common/pathList.vue')['default']
    RecommendList: typeof import('./src/components/common/recommendList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('./src/components/tag.vue')['default']
    TagGroup: typeof import('./src/components/tagGroup.vue')['default']
    Ticket_qingxin: typeof import('./src/components/ticket/ticket_qingxin.vue')['default']
    TicketDetail: typeof import('./src/components/ticket-detail/ticket-detail.vue')['default']
    Tour_qingxin: typeof import('./src/components/tour/tour_qingxin.vue')['default']
    Weather: typeof import('./src/components/weather.vue')['default']
  }
}
