export default {
  project: {
    project_name: 'demo',
    buyer_need_realname: true,
    player_need_realname: false,
    using_shopping_cart: false,
    purchase_protocol:
      '<p style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0.62em 0px; border: none; word-break: break-all; overflow-wrap: break-word; line-height: 24px; text-indent: 2em; color: #333333; font-family: Tahoma, \'Microsoft YaHei\', Geneva, sans-serif; font-size: 14px;"><span style="color: #333333; font-family: Tahoma, Microsoft YaHei, Geneva, sans-serif;"><span style="font-size: 14px;">您只有无条件接受以下所有服务条款，才能继续申请：</span></span></p>\n<p style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0.62em 0px; border: none; word-break: break-all; overflow-wrap: break-word; line-height: 24px; text-indent: 2em; color: #333333; font-family: Tahoma, \'Microsoft YaHei\', Geneva, sans-serif; font-size: 14px;"><span style="color: #333333; font-family: Tahoma, Microsoft YaHei, Geneva, sans-serif;"><span style="font-size: 14px;">一、服务条款的确认和接纳</span></span></p>\n<p style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0.62em 0px; border: none; word-break: break-all; overflow-wrap: break-word; line-height: 24px; text-indent: 2em; color: #333333; font-family: Tahoma, \'Microsoft YaHei\', Geneva, sans-serif; font-size: 14px;"><span style="color: #333333; font-family: Tahoma, Microsoft YaHei, Geneva, sans-serif;"><span style="font-size: 14px;">水车坪旅游网的所有权和运作权归婺源旅游网信息技术有限责任公司所有。用户通过完成注册程序并点击一下&ldquo;我同意&rdquo;的按钮，这表示用户与亚布力滑雪旅游度假区达成协议并接受所有的服务条款。</span></span></p>\n<p style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0.62em 0px; border: none; word-break: break-all; overflow-wrap: break-word; line-height: 24px; text-indent: 2em; color: #333333; font-family: Tahoma, \'Microsoft YaHei\', Geneva, sans-serif; font-size: 14px;">一、服务条款的确认和接纳</p>\n<p style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0.62em 0px; border: none; word-break: break-all; overflow-wrap: break-word; line-height: 24px; text-indent: 2em; color: #333333; font-family: Tahoma, \'Microsoft YaHei\', Geneva, sans-serif; font-size: 14px;">&nbsp;</p>\n<p style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0.62em 0px; border: none; word-break: break-all; overflow-wrap: break-word; line-height: 24px; text-indent: 2em; color: #333333; font-family: Tahoma, \'Microsoft YaHei\', Geneva, sans-serif; font-size: 14px;">水车坪旅游网的所有权和运作权归婺源旅游网信息技术有限责任公司所有。用户通过完成注册程序并点击一下&ldquo;我同意&rdquo;的按钮，这表示用户与亚布力滑雪旅游度假区达成协议并接受所有的服务条款。</p>\n<p style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0.62em 0px; border: none; word-break: break-all; overflow-wrap: break-word; line-height: 24px; text-indent: 2em; color: #333333; font-family: Tahoma, \'Microsoft YaHei\', Geneva, sans-serif; font-size: 14px;">一、服务条款的确认和接纳</p>\n<p style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0.62em 0px; border: none; word-break: break-all; overflow-wrap: break-word; line-height: 24px; text-indent: 2em; color: #333333; font-family: Tahoma, \'Microsoft YaHei\', Geneva, sans-serif; font-size: 14px;">&nbsp;</p>\n<p style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0.62em 0px; border: none; word-break: break-all; overflow-wrap: break-word; line-height: 24px; text-indent: 2em; color: #333333; font-family: Tahoma, \'Microsoft YaHei\', Geneva, sans-serif; font-size: 14px;">&nbsp;</p>\n<p style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0.62em 0px; border: none; word-break: break-all; overflow-wrap: break-word; line-height: 24px; text-indent: 2em; color: #333333; font-family: Tahoma, \'Microsoft YaHei\', Geneva, sans-serif; font-size: 14px;">水车坪旅游网的所有权和运作权归婺源旅游网信息技术有限责任公司所有。用户通过完成注册程序并点击一下&ldquo;我同意&rdquo;的按钮，这表示用户与亚布力滑雪旅游度假区达成协议并接受所有的服务条款。111111111111111111</p>\n<p style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0.62em 0px; border: none; word-break: break-all; overflow-wrap: break-word; line-height: 24px; text-indent: 2em; color: #333333; font-family: Tahoma, \'Microsoft YaHei\', Geneva, sans-serif; font-size: 14px;">11</p>\n<p style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0.62em 0px; border: none; word-break: break-all; overflow-wrap: break-word; line-height: 24px; text-indent: 2em; color: #333333; font-family: Tahoma, \'Microsoft YaHei\', Geneva, sans-serif; font-size: 14px;">&nbsp;</p>',
    member_purchase_protocol:
      '<p class="MsoNormal" style="mso-margin-top-alt: auto; text-align: left; text-indent: 24.0pt; line-height: 18.0pt; mso-pagination: widow-orphan; word-break: break-all;" align="left"><span style="font-size: 9.0pt; font-family: 宋体; mso-ascii-font-family: inherit; mso-hansi-font-family: inherit; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">会员下单协议</span><span lang="EN-US" style="font-size: 9.0pt; font-family: \'inherit\',serif; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">&nbsp;&nbsp;</span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">您只有无条件接受以下所有服务条款，才能继续申请：</span></p>\n<p class="MsoNormal" style="mso-margin-top-alt: auto; text-align: left; text-indent: 24.0pt; line-height: 18.0pt; mso-pagination: widow-orphan; word-break: break-all;" align="left"><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">一、服务条款的确认和接纳</span></p>\n<p class="MsoNormal" style="mso-margin-top-alt: auto; text-align: left; text-indent: 24.0pt; line-height: 18.0pt; mso-pagination: widow-orphan; word-break: break-all;" align="left"><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">水车坪旅游网的所有权和运作权归婺源旅游网信息技术有限责任公司所有。用户通过完成注册程序并点击一下</span><span lang="EN-US" style="mso-bidi-font-size: 10.5pt; font-family: \'Tahoma\',sans-serif; color: #333333; mso-font-kerning: 0pt;">&ldquo;</span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">我同意</span><span lang="EN-US" style="mso-bidi-font-size: 10.5pt; font-family: \'Tahoma\',sans-serif; color: #333333; mso-font-kerning: 0pt;">&rdquo;</span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">的按钮，这表示用户与亚布力滑雪旅游度假区达成协议并接受所有的服务条款。</span></p>\n<p class="MsoNormal" style="mso-margin-top-alt: auto; text-align: left; text-indent: 24.0pt; line-height: 18.0pt; mso-pagination: widow-orphan; word-break: break-all;" align="left"><span lang="EN-US" style="mso-bidi-font-size: 10.5pt; font-family: \'Tahoma\',sans-serif; color: #333333; mso-font-kerning: 0pt;">(3)</span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">自行配备上网的所需设备，</span><span style="mso-bidi-font-size: 10.5pt; font-family: \'Tahoma\',sans-serif; color: #333333; mso-font-kerning: 0pt;"> </span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">包括个人电脑、调制解调器或其他必备上网装置。</span></p>\n<p class="MsoNormal" style="mso-margin-top-alt: auto; text-align: left; text-indent: 24.0pt; line-height: 18.0pt; mso-pagination: widow-orphan; word-break: break-all;" align="left"><span lang="EN-US" style="mso-bidi-font-size: 10.5pt; font-family: \'Tahoma\',sans-serif; color: #333333; mso-font-kerning: 0pt;">(4)</span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">自行负担个人上网所支付的与此服务有关的电话费用、</span><span style="mso-bidi-font-size: 10.5pt; font-family: \'Tahoma\',sans-serif; color: #333333; mso-font-kerning: 0pt;"> </span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">网络费用。</span></p>\n<p class="MsoNormal" style="mso-margin-top-alt: auto; text-align: left; text-indent: 24.0pt; line-height: 18.0pt; mso-pagination: widow-orphan; word-break: break-all;" align="left"><span lang="EN-US" style="mso-bidi-font-size: 10.5pt; font-family: \'Tahoma\',sans-serif; color: #333333; mso-font-kerning: 0pt;">4</span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">、会员的帐号、密码和安全性</span></p>\n<p class="MsoNormal" style="mso-margin-top-alt: auto; text-align: left; text-indent: 24.0pt; line-height: 18.0pt; mso-pagination: widow-orphan; word-break: break-all;" align="left"><span lang="EN-US" style="mso-bidi-font-size: 10.5pt; font-family: \'Tahoma\',sans-serif; color: #333333; mso-font-kerning: 0pt;">(3)</span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">自行配备上网的所需设备，</span><span style="mso-bidi-font-size: 10.5pt; font-family: \'Tahoma\',sans-serif; color: #333333; mso-font-kerning: 0pt;"> </span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">包括个人电脑、调制解调器或其他必备上网装置。</span></p>\n<p class="MsoNormal" style="mso-margin-top-alt: auto; text-align: left; text-indent: 24.0pt; line-height: 18.0pt; mso-pagination: widow-orphan; word-break: break-all;" align="left"><span lang="EN-US" style="mso-bidi-font-size: 10.5pt; font-family: \'Tahoma\',sans-serif; color: #333333; mso-font-kerning: 0pt;">(4)</span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">自行负担个人上网所支付的与此服务有关的电话费用、</span><span style="mso-bidi-font-size: 10.5pt; font-family: \'Tahoma\',sans-serif; color: #333333; mso-font-kerning: 0pt;"> </span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">网络费用。</span></p>\n<p class="MsoNormal" style="mso-margin-top-alt: auto; text-align: left; text-indent: 24.0pt; line-height: 18.0pt; mso-pagination: widow-orphan; word-break: break-all;" align="left"><span lang="EN-US" style="mso-bidi-font-size: 10.5pt; font-family: \'Tahoma\',sans-serif; color: #333333; mso-font-kerning: 0pt;">4</span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">、会员的帐号、密码和安全性</span></p>\n<p class="MsoNormal" style="mso-margin-top-alt: auto; text-align: left; text-indent: 24.0pt; line-height: 18.0pt; mso-pagination: widow-orphan; word-break: break-all;" align="left"><span lang="EN-US" style="mso-bidi-font-size: 10.5pt; font-family: \'Tahoma\',sans-serif; color: #333333; mso-font-kerning: 0pt;">(3)</span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">自行配备上网的所需设备，</span><span style="mso-bidi-font-size: 10.5pt; font-family: \'Tahoma\',sans-serif; color: #333333; mso-font-kerning: 0pt;"> </span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">包括个人电脑、调制解调器或其他必备上网装置。</span></p>\n<p class="MsoNormal" style="mso-margin-top-alt: auto; text-align: left; text-indent: 24.0pt; line-height: 18.0pt; mso-pagination: widow-orphan; word-break: break-all;" align="left"><span lang="EN-US" style="mso-bidi-font-size: 10.5pt; font-family: \'Tahoma\',sans-serif; color: #333333; mso-font-kerning: 0pt;">(4)</span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">自行负担个人上网所支付的与此服务有关的电话费用、</span><span style="mso-bidi-font-size: 10.5pt; font-family: \'Tahoma\',sans-serif; color: #333333; mso-font-kerning: 0pt;"> </span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">网络费用。</span></p>\n<p class="MsoNormal" style="mso-margin-top-alt: auto; text-align: left; text-indent: 24.0pt; line-height: 18.0pt; mso-pagination: widow-orphan; word-break: break-all;" align="left"><span lang="EN-US" style="mso-bidi-font-size: 10.5pt; font-family: \'Tahoma\',sans-serif; color: #333333; mso-font-kerning: 0pt;">4</span><span style="mso-bidi-font-size: 10.5pt; font-family: 宋体; mso-ascii-font-family: Tahoma; mso-hansi-font-family: Tahoma; mso-bidi-font-family: Tahoma; color: #333333; mso-font-kerning: 0pt;">、会员的帐号、密码和安全性</span></p>',
    refund_notice:
      '<p class="MsoNormal" style="text-indent: 22.0pt; mso-char-indent-count: 2.0; layout-grid-mode: char; mso-layout-grid-align: none;"><strong><span style="font-size: 11.0pt; font-family: 仿宋_GB2312;">退改签说明</span></strong></p>\n<p class="MsoNormal" style="text-indent: 22.0pt; mso-char-indent-count: 2.0; layout-grid-mode: char; mso-layout-grid-align: none;"><span lang="EN-US" style="font-size: 11.0pt; font-family: 仿宋_GB2312;">1</span><span style="font-size: 11.0pt; font-family: 仿宋_GB2312;">、对于购买预售门票的游客，预售门票在未使用的情况下，可在购票平台于门票标示入场时间之前申请退款，经景区核对订单信息后，购票款将于<span lang="EN-US">48</span>小时内原途径退回，不收取手续费。</span></p>\n<p class="MsoNormal" style="text-indent: 22.0pt; mso-char-indent-count: 2.0; layout-grid-mode: char; mso-layout-grid-align: none;"><span lang="EN-US" style="font-size: 11.0pt; font-family: 仿宋_GB2312;">2</span><span style="font-size: 11.0pt; font-family: 仿宋_GB2312;">、预售门票在未使用的情况下，入场时间至游览日<span lang="EN-US">24</span>点前申请退款，景区将收取<span lang="EN-US">10%</span>手续费。</span></p>\n<p class="MsoNormal" style="text-indent: 22.0pt; mso-char-indent-count: 2.0; layout-grid-mode: char; mso-layout-grid-align: none;"><span lang="EN-US" style="font-size: 11.0pt; font-family: 仿宋_GB2312;">3</span><span style="font-size: 11.0pt; font-family: 仿宋_GB2312;">、多人订单在验票时，任意一人验票成功后，订单内所有游客均视为已验票，无法申请退款。</span></p>\n<p class="MsoNormal" style="text-indent: 22.0pt; mso-char-indent-count: 2.0; layout-grid-mode: char; mso-layout-grid-align: none;"><span lang="EN-US" style="font-size: 11.0pt; font-family: 仿宋_GB2312;">4</span><span style="font-size: 11.0pt; font-family: 仿宋_GB2312;">、因恶劣天气、电力、设备等不可抗因素，为确保安全，摩天轮景区将暂停开放，未乘坐的游客可免费退票。您可在公众号的&ldquo;系统公告&rdquo;中点击查询景区当前运营开放状态。</span></p>\n<p class="MsoNormal" style="text-indent: 22.0pt; mso-char-indent-count: 2.0; layout-grid-mode: char; mso-layout-grid-align: none;"><span lang="EN-US" style="font-size: 11.0pt; font-family: 仿宋_GB2312;">5</span><span style="font-size: 11.0pt; font-family: 仿宋_GB2312;">、如游客已乘坐，不能以游览能见度、雨雾等天气情况作为退票理由。</span></p>\n<p class="MsoNormal" style="text-indent: 22.0pt; mso-char-indent-count: 2.0; layout-grid-mode: char; mso-layout-grid-align: none;"><span lang="EN-US" style="font-size: 11.0pt; font-family: 仿宋_GB2312;">6</span><span style="font-size: 11.0pt; font-family: 仿宋_GB2312;">、对于已验票入场，因自身原因未登舱乘坐的游客，一律不办理退票。</span></p>\n<p class="MsoNormal" style="text-indent: 22.0pt; mso-char-indent-count: 2.0; layout-grid-mode: char; mso-layout-grid-align: none;"><span lang="EN-US" style="font-size: 11.0pt; font-family: 仿宋_GB2312;">7</span><span style="font-size: 11.0pt; font-family: 仿宋_GB2312;">、游客可于游览日<span lang="EN-US">24</span>点前进行门票改签，每订单只限改签一次，不收取手续费。只能改签至<span lang="EN-US">3</span>日内有剩余门票场次，且需票价相同。改签后的门票一律不办理退款。</span></p>\n<p class="MsoNormal" style="text-indent: 22.0pt; mso-char-indent-count: 2.0; layout-grid-mode: char; mso-layout-grid-align: none;"><span lang="EN-US" style="font-size: 11.0pt; font-family: 仿宋_GB2312;">8</span><span style="font-size: 11.0pt; font-family: 仿宋_GB2312;">、预售门票在游览日<span lang="EN-US">24</span>点后一律不办理退票，造成的损失由游客自行承担。</span></p>',
    admission_notice:
      '<p class="MsoNormal" style="text-align: center; text-indent: 14.55pt;" align="center"><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">晋祠景区入园预约须知</span></p>\n<p class="MsoNormal" style="text-indent: 14.55pt;"><span lang="EN-US" style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">&nbsp;</span></p>\n<p class="MsoNormal"><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">入园时间：<span lang="EN-US">08:30</span>&mdash;<span lang="EN-US">18:00<span style="mso-spacerun: yes;">&nbsp; </span></span>（全年）</span></p>\n<p class="MsoNormal"><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">入园地址：景区东大门<span lang="EN-US"><span style="mso-spacerun: yes;">&nbsp; </span></span>南门</span></p>\n<p class="MsoNormal"><span lang="EN-US" style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">&nbsp;</span></p>\n<p class="MsoNormal"><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">预约流程：</span></p>\n<p class="MsoNormal"><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">关注官方微信公众号&ldquo;太原市晋祠公园&rdquo;&rarr;入园免费预约&rarr;自助&ldquo;<span lang="EN-US">0</span>元&rdquo;购票&rarr;立即预约&rarr;填写相关信息&rarr;完成预约</span></p>\n<p class="MsoNormal"><span lang="EN-US" style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">&nbsp;</span></p>\n<p class="MsoNormal"><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">入园须知：</span></p>\n<p class="MsoNormal" style="margin-left: 0cm; text-indent: 0cm; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-US" style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;"><span style="mso-list: Ignore;">1、</span></span><!--[endif]--><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">我园实行线上免费实名预约（中高风险地区不可线上购票），请游客提前预约，坚持无预约不入园，间隔错峰游览，接待量不超过最大承载量<span lang="EN-US">75% </span>。</span></p>\n<p class="MsoNormal" style="margin-left: 0cm; text-indent: 0cm; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-US" style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;"><span style="mso-list: Ignore;">2、</span></span><!--[endif]--><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">预约成功后凭二维码或身份证在入口闸机检票，人证合一方可入园，没有预约的游客将不能入园。</span></p>\n<p class="MsoNormal" style="margin-left: 0cm; text-indent: 0cm; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-US" style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;"><span style="mso-list: Ignore;">3、</span></span><!--[endif]--><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">入园时请携带个人有效证件、佩戴口罩，配合景区实名登记、核验健康码、测量体温，间隔一米距离，有序排队等疫情防控各项措施。</span></p>\n<p class="MsoNormal"><span lang="EN-US" style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">4</span><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">、爱护文物、公共设施、花草树木，不要在树木、名胜古迹和公共设施上涂抹、刻画。</span></p>\n<p class="MsoNormal"><span lang="EN-US" style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">5</span><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">、请自觉遵守景区安全管理规定，在景区内照顾好老人和小孩，保管好您的随身物品。</span></p>\n<p class="MsoNormal"><span lang="EN-US" style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">6</span><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">、游客进入景区后要注意文明礼仪和个人卫生<span lang="EN-US">,</span>咳嗽、打喷嚏时用胳膊肘掩护。</span></p>\n<p class="MsoNormal"><span lang="EN-US" style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">7</span><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">、请广大游客出游前务必提前了解景区接待情况并预约，配合景区工作人员做好各类疫情防控、流量管控、安全管控等工作。</span></p>\n<p class="MsoNormal"><span lang="EN-US" style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">8</span><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">、根据省、市疫情防控小组的通知，<span lang="EN-US">14</span>天内来自国内中高风险区及入境人员谢绝入园参观。体温&ge;<span lang="EN-US">37.2</span>℃，或有咳嗽、气短、胸闷等症状的游客谢绝入园。</span></p>\n<p class="MsoNormal"><span lang="EN-US" style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">&nbsp;</span></p>\n<p class="MsoNormal"><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">享受免预约人群：</span></p>\n<p class="MsoNormal"><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">（一）对<span lang="EN-US">60</span>周岁（含<span lang="EN-US">60</span>周岁）以上老年人凭本人身份证或老年证予以免预约。</span></p>\n<p class="MsoNormal"><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">（二）对<span lang="EN-US">6</span>周岁（含<span lang="EN-US">6</span>周岁）以下或身高<span lang="EN-US">1.2</span>米（含<span lang="EN-US">1.2</span>米）以下的儿童予以免预约。</span></p>\n<p class="MsoNormal"><span lang="EN-US" style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;"><span style="mso-spacerun: yes;">&nbsp; </span></span></p>\n<p class="MsoNormal"><span style="font-size: 16.0pt; font-family: 仿宋; mso-bidi-font-family: 仿宋;">晋祠公园预约咨询电话：<span lang="EN-US">0351</span>&mdash;<span lang="EN-US">6020038</span></span></p>\n<p class="MsoNormal">&nbsp;</p>',
    support_identity_type: ['ID_CARD', 'HUZHAO', 'GANGAO', 'TAIBAO'],
    allow_user_part_cancel: true,
    allow_user_cancel_part_use: true,
    scenic_type: 'ALL',
    goods_service_name: '便民服务（仅供博物馆使用）',
    goods_service: true,
    wx_miniprogram_userinfo: true,
    show_purchase_protocol_separate: true,
    upload_health_code: 0,
    upload_health_code_desc: '上传健康码/行程码',
    ali_miniprogram_auth_mode: 'auth_base',
    promissory_note_allow_choose_time: false,
  },
  scenicList: {
    total: 18,
    list: [
      {
        id: 83,
        status: 'active',
        name: '蜀南竹海test',
        subtitle: null,
        address: '宜宾',
        opening_time: null,
        min_price: 0,
        worktime_permit_first: false,
        worktimes: [
          {
            type: 'SPECIAL_WEEKDAY',
            permit: true,
            priority: 0,
            no_permit_prompt: '景区已关闭',
            day: 0,
            periods: [
              {
                start: '09:00:00',
                end: '18:00:00',
              },
            ],
          },
          {
            type: 'SPECIAL_WEEKDAY',
            permit: true,
            priority: 0,
            no_permit_prompt: '景区已关闭',
            day: 1,
            periods: [
              {
                start: '09:00:00',
                end: '18:00:00',
              },
            ],
          },
          {
            type: 'SPECIAL_WEEKDAY',
            permit: true,
            priority: 0,
            no_permit_prompt: '景区已关闭',
            day: 2,
            periods: [
              {
                start: '09:00:00',
                end: '18:00:00',
              },
            ],
          },
          {
            type: 'SPECIAL_WEEKDAY',
            permit: true,
            priority: 0,
            no_permit_prompt: '景区已关闭',
            day: 3,
            periods: [
              {
                start: '09:00:00',
                end: '18:00:00',
              },
            ],
          },
          {
            type: 'SPECIAL_WEEKDAY',
            permit: true,
            priority: 0,
            no_permit_prompt: '景区已关闭',
            day: 4,
            periods: [
              {
                start: '09:00:00',
                end: '18:00:00',
              },
            ],
          },
          {
            type: 'SPECIAL_WEEKDAY',
            permit: true,
            priority: 0,
            no_permit_prompt: '景区已关闭',
            day: 6,
            periods: [
              {
                start: '09:00:00',
                end: '18:00:00',
              },
            ],
          },
        ],
        pictures: [
          {
            url: 'https://pmgtdev.cleartv.cn/download/790d82ee8952423ccb2eba16898d04ce_6kMyjLnl_230302160404',
            size: 88912,
          },
          {
            url: 'https://pmgtdev.cleartv.cn/download/2c29b8c18d77c0329eda54d887eef713_wU14FHsv_230302160531',
            size: 105509,
          },
          {
            url: 'https://pmgtdev.cleartv.cn/download/53aa9206abc8640122b0a6b435b9c345_5OmFkrvH_230302160537',
            size: 80310,
          },
          {
            url: 'https://pmgtdev.cleartv.cn/download/91283ba162a78d3fb8e1d152ff765ff4_RWxJX6J1_230302160542',
            size: 63923,
          },
        ],
        tags: [
          {
            id: 6,
            name: '停车场',
            description: '',
          },
          {
            id: 7,
            name: '卫生间',
            description: '',
          },
          {
            id: 13,
            name: '餐厅',
            description: '',
          },
          {
            id: 50,
            name: 'WiFi',
            description: 'wifi',
          },
          {
            id: 54,
            name: '吸烟区',
            description: 'smoke',
          },
          {
            id: 55,
            name: '母婴室',
            description: 'mom',
          },
          {
            id: 56,
            name: '商场购物',
            description: 'shopping',
          },
        ],
      },
      {
        id: 82,
        status: 'active',
        name: '南水北调',
        subtitle: null,
        address: '123',
        opening_time: null,
        min_price: 0,
        worktime_permit_first: false,
        worktimes: [
          {
            type: 'SPECIAL_DAY',
            permit: true,
            priority: 0,
            no_permit_prompt: null,
            start: '2022-10-24',
            end: '2031-11-28',
            periods: [
              {
                start: '08:00:00',
                end: '20:00:00',
              },
            ],
          },
        ],
        pictures: null,
        tags: [],
      },
      {
        id: 81,
        status: 'active',
        name: '河北演示间',
        subtitle: null,
        address: '河北',
        opening_time: null,
        min_price: 0,
        worktime_permit_first: false,
        worktimes: [
          {
            type: 'SPECIAL_DAY',
            permit: true,
            priority: 0,
            no_permit_prompt: null,
            start: '2022-10-22',
            end: '2032-09-20',
            periods: [
              {
                start: '08:00:00',
                end: '20:00:00',
              },
            ],
          },
        ],
        pictures: null,
        tags: [],
      },
      {
        id: 80,
        status: 'active',
        name: '云梦山',
        subtitle: null,
        address: '仙门山',
        opening_time: null,
        min_price: 0,
        worktime_permit_first: false,
        worktimes: [
          {
            type: 'SPECIAL_DAY',
            permit: true,
            priority: 0,
            no_permit_prompt: null,
            start: '2022-09-02',
            end: '2026-10-04',
            periods: [
              {
                start: '08:00:00',
                end: '20:00:00',
              },
            ],
          },
        ],
        pictures: null,
        tags: [],
      },
      {
        id: 79,
        status: 'active',
        name: '葫芦古镇',
        subtitle: null,
        address: '葫芦古镇',
        opening_time: null,
        min_price: 0,
        worktime_permit_first: false,
        worktimes: [
          {
            type: 'SPECIAL_DAY',
            permit: true,
            priority: 0,
            no_permit_prompt: null,
            start: '2022-09-22',
            end: '2025-10-04',
            periods: [
              {
                start: '08:00:00',
                end: '20:00:00',
              },
            ],
          },
        ],
        pictures: [
          {
            url: 'https://pmgtdev.cleartv.cn/download/2f76725a3a60c4222032774f2fb0e340_HStgKcFJ_220718081543',
            size: 67640,
          },
          {
            url: 'https://pmgtdev.cleartv.cn/download/dd448a4e3ffa0c151e3139bf9e63cba2_UAJeWC84_220718081555',
            size: 91223,
          },
        ],
        tags: [],
      },
      {
        id: 78,
        status: 'active',
        name: '新疆维吾尔自治区',
        subtitle: null,
        address: '新疆维吾尔自治区-伊犁哈萨克自治州-新源县-青年街013号',
        opening_time: null,
        min_price: 5,
        worktime_permit_first: false,
        worktimes: [
          {
            type: 'LEGAL_HOLIDAY',
            permit: true,
            priority: 0,
            no_permit_prompt: null,
            legal_type: 'HOLIDAY',
            periods: [
              {
                start: '08:00:00',
                end: '20:00:00',
              },
            ],
          },
        ],
        pictures: [
          {
            url: 'https://pmgtdev.cleartv.cn/download/79b9f5ab0aae80d59894d386703eed14_AOXeU9GK_220712163123',
            size: 48968,
          },
        ],
        tags: [],
      },
      {
        id: 75,
        status: 'active',
        name: '洞爷湖',
        subtitle: null,
        address: '健身房看见了说法是',
        opening_time: null,
        min_price: 0,
        worktime_permit_first: false,
        worktimes: [
          {
            type: 'SPECIAL_DAY',
            permit: true,
            priority: 0,
            no_permit_prompt: null,
            start: '2022-04-18',
            end: '2024-06-28',
            periods: [
              {
                start: '00:00:00',
                end: '20:00:00',
              },
            ],
          },
        ],
        pictures: null,
        tags: [],
      },
      {
        id: 76,
        status: 'active',
        name: '河南办事处景点',
        subtitle: null,
        address: '河南办事处景点',
        opening_time: null,
        min_price: 0,
        worktime_permit_first: false,
        worktimes: [
          {
            type: 'SPECIAL_DAY',
            permit: true,
            priority: 0,
            no_permit_prompt: null,
            start: '2022-05-12',
            end: '2027-06-18',
            periods: [
              {
                start: '00:00:00',
                end: '23:00:00',
              },
            ],
          },
        ],
        pictures: [
          {
            url: 'https://pmgtdev.cleartv.cn/download/47c1059c0a48ce1e4617f37da6c42c57_GWVYZBlH_220513150652',
            size: 35052,
          },
        ],
        tags: [],
      },
      {
        id: 66,
        status: 'active',
        name: '上海城市展示规划馆',
        subtitle: null,
        address: '景舒苑3村12号603',
        opening_time: null,
        min_price: 0,
        worktime_permit_first: false,
        worktimes: [
          {
            type: 'SPECIAL_DAY',
            permit: true,
            priority: 0,
            no_permit_prompt: null,
            start: '2021-11-09',
            end: '2023-12-31',
            periods: [
              {
                start: '00:00:00',
                end: '20:00:00',
              },
            ],
          },
          {
            type: 'SPECIAL_DAY',
            permit: true,
            priority: 10,
            no_permit_prompt: null,
            start: '2022-04-08',
            end: '2025-05-31',
            periods: [
              {
                start: '08:00:00',
                end: '20:00:00',
              },
            ],
          },
          {
            type: 'SPECIAL_WEEKDAY',
            permit: false,
            priority: 0,
            no_permit_prompt: null,
            day: 0,
            periods: [
              {
                start: '08:00:00',
                end: '20:00:00',
              },
            ],
          },
          {
            type: 'SPECIAL_WEEKDAY',
            permit: false,
            priority: 1,
            no_permit_prompt: null,
            day: 1,
            periods: [
              {
                start: '08:00:00',
                end: '20:00:00',
              },
            ],
          },
          {
            type: 'SPECIAL_WEEKDAY',
            permit: false,
            priority: 1,
            no_permit_prompt: '周三,周五景区关闭',
            day: 2,
            periods: [
              {
                start: '08:00:00',
                end: '20:00:00',
              },
            ],
          },
          {
            type: 'SPECIAL_WEEKDAY',
            permit: false,
            priority: 1,
            no_permit_prompt: '周三,周五景区关闭',
            day: 4,
            periods: [
              {
                start: '08:00:00',
                end: '20:00:00',
              },
            ],
          },
        ],
        pictures: null,
        tags: [],
      },
      {
        id: 68,
        status: 'active',
        name: '狼山景区',
        subtitle: null,
        address: '213',
        opening_time: null,
        min_price: 0,
        worktime_permit_first: false,
        worktimes: [
          {
            type: 'SPECIAL_DAY',
            permit: true,
            priority: 0,
            no_permit_prompt: null,
            start: '2021-11-26',
            end: '2024-12-12',
            periods: [
              {
                start: '08:00:00',
                end: '20:00:00',
              },
            ],
          },
        ],
        pictures: [
          {
            url: 'https://pmgtdev.cleartv.cn/download/9b4d358e4251171094ea9aaea7a24a4e_6mRWimS2_220112112823',
            size: 72999,
          },
          {
            url: 'https://pmgtdev.cleartv.cn/download/977914f61316acbb84e0926b84939780_V0rCpUui_220112112828',
            size: 89874,
          },
        ],
        tags: [],
      },
    ],
    pageNum: 1,
    pageSize: 10,
    size: 10,
    startRow: 1,
    endRow: 10,
    pages: 2,
    prePage: 0,
    nextPage: 2,
    isFirstPage: true,
    isLastPage: false,
    hasPreviousPage: false,
    hasNextPage: true,
    navigatePages: 8,
    navigatepageNums: [1, 2],
    navigateFirstPage: 1,
    navigateLastPage: 2,
  },
  ticketList: {
    total: 1,
    list: [
      {
        id: 427,
        type: 'TICKET',
        is_ticket_face: 0,
        is_member_online: 0,
        is_member_online_face: 0,
        card_pic: '',
        person_num: 1,
        need_realname: 0,
        player_need_realname: 0,
        purchase_separate: 'NONE',
        name: '蜀南竹海测试',
        description:
          '<div class="tee-view e-card-intro-item" style="margin-bottom: 24px; font-size: 14px; color: #323233; font-family: -apple-system, BlinkMacSystemFont, \'Helvetica Neue\', Helvetica, \'Segoe UI\', Arial, Roboto, \'PingFang SC\', miui, \'Hiragino Sans GB\', \'Microsoft Yahei\', sans-serif; background-color: #ffffff;" data-v-838c9cc="">\n<div class="tee-view rule-label" style="margin-bottom: 8px; line-height: 18px;" data-v-838c9cc=""><strong>有效期</strong></div>\n<div class="tee-view rule-list" style="line-height: 18px; color: #969799; white-space: pre-wrap;" data-v-838c9cc=""><span style="color: #e03e2d;">2023年01月14日 - 2023年12月31日</span>内使用有效</div>\n</div>\n<div class="tee-view e-card-intro-item" style="margin-bottom: 24px; font-size: 14px; color: #323233; font-family: -apple-system, BlinkMacSystemFont, \'Helvetica Neue\', Helvetica, \'Segoe UI\', Arial, Roboto, \'PingFang SC\', miui, \'Hiragino Sans GB\', \'Microsoft Yahei\', sans-serif; background-color: #ffffff;" data-v-838c9cc="">\n<div class="tee-view rule-label" style="margin-bottom: 8px; line-height: 18px;" data-v-838c9cc=""><strong>生效时间</strong></div>\n<div class="tee-view rule-list" style="line-height: 18px; color: #969799; white-space: pre-wrap;" data-v-838c9cc="">购买后立即生效</div>\n</div>\n<div class="tee-view e-card-intro-item" style="margin-bottom: 24px; font-size: 14px; color: #323233; font-family: -apple-system, BlinkMacSystemFont, \'Helvetica Neue\', Helvetica, \'Segoe UI\', Arial, Roboto, \'PingFang SC\', miui, \'Hiragino Sans GB\', \'Microsoft Yahei\', sans-serif; background-color: #ffffff;" data-v-838c9cc="">\n<div class="tee-view rule-label" style="margin-bottom: 8px; line-height: 18px;" data-v-838c9cc=""><strong>节假日</strong></div>\n<div class="tee-view rule-list" style="line-height: 18px; color: #969799; white-space: pre-wrap;" data-v-838c9cc="">节假日可用</div>\n</div>\n<div class="tee-view e-card-intro-item" style="margin-bottom: 24px; font-size: 14px; color: #323233; font-family: -apple-system, BlinkMacSystemFont, \'Helvetica Neue\', Helvetica, \'Segoe UI\', Arial, Roboto, \'PingFang SC\', miui, \'Hiragino Sans GB\', \'Microsoft Yahei\', sans-serif; background-color: #ffffff;" data-v-838c9cc="">\n<div class="tee-view rule-label" style="margin-bottom: 8px; line-height: 18px;" data-v-838c9cc=""><strong>售后服务</strong></div>\n<div class="tee-view rule-list" style="line-height: 18px; color: #969799; white-space: pre-wrap;" data-v-838c9cc="">支持申请退款</div>\n</div>\n<div class="tee-view e-card-intro-item" style="margin-bottom: 24px; font-size: 14px; color: #323233; font-family: -apple-system, BlinkMacSystemFont, \'Helvetica Neue\', Helvetica, \'Segoe UI\', Arial, Roboto, \'PingFang SC\', miui, \'Hiragino Sans GB\', \'Microsoft Yahei\', sans-serif; background-color: #ffffff;" data-v-838c9cc="">\n<div class="tee-view rule-label" style="margin-bottom: 8px; line-height: 18px;" data-v-838c9cc="">&nbsp;</div>\n</div>',
        price: 1,
        price_original: 100,
        is_book_today: 1,
        book_today_endtime: '23:59:59',
        book_future_days: 30,
        book_min: 1,
        book_max: 100,
        is_restricted_sales: 0,
        sales_volume: null,
        is_refund: 1,
        refund_advance_days: -10,
        refund_today_endtime: '23:59:59',
        sell_startdate: '2023-03-06',
        sell_enddate: '2033-03-06',
        sale_time_start: '00:00:00',
        sale_time_end: '23:59:59',
        advance_days: 0,
        delay_days: 0,
        use_startdate: '2023-04-14',
        use_enddate: '2033-04-14',
        use_time_start: '00:00:00',
        use_time_end: '23:59:59',
        use_valid_days: 1,
        purchase_notice:
          "<p style=\"margin: 0px 0px 1em; color: #333333; font-family: -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, 'Segoe UI', Arial, Roboto, 'PingFang SC', miui, 'Hiragino Sans GB', 'Microsoft Yahei', sans-serif; font-size: 16px; line-height: 1.5em;\"><span style=\"font-size: 14px; color: #000000;\"><span style=\"font-weight: bold;\"><span style=\"font-family: 宋体;\">➢</span>产品内容：<strong>蜀南竹海一日游门票</strong></span></span></p>\n<p style=\"margin: 0px 0px 1em; color: #333333; font-family: -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, 'Segoe UI', Arial, Roboto, 'PingFang SC', miui, 'Hiragino Sans GB', 'Microsoft Yahei', sans-serif; font-size: 16px; line-height: 1.5em;\"><span style=\"font-size: 14px; color: #000000;\"><span style=\"font-weight: bold;\"><span style=\"font-family: 宋体;\">➢</span>使用时间：</span>即日起至12月31日</span></p>\n<p style=\"margin: 0px 0px 1em; color: #333333; font-family: -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, 'Segoe UI', Arial, Roboto, 'PingFang SC', miui, 'Hiragino Sans GB', 'Microsoft Yahei', sans-serif; font-size: 16px; line-height: 1.5em;\"><span style=\"font-size: 14px; color: #000000;\"><span style=\"font-weight: bold;\"><span style=\"font-family: 宋体;\">➢</span>营业时间：</span><span style=\"font-weight: bold;\">24小时营业</span><br /></span></p>\n<p style=\"margin: 0px 0px 1em; color: #333333; font-family: -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, 'Segoe UI', Arial, Roboto, 'PingFang SC', miui, 'Hiragino Sans GB', 'Microsoft Yahei', sans-serif; font-size: 16px; line-height: 1.5em;\"><span style=\"color: #000000;\"><span style=\"font-weight: bold;\"><span style=\"font-size: 14px;\"><span style=\"font-family: 宋体;\">➢</span>扫码入园：下单成功后，会生成订单二维码，将此二维码，对准竹尖漫步入闸机扫描口，即可识别入园<br />注：若一个订单购买多张票的（一个二维码，多个核销码），请务必依次排好队，遵从工作人员的指导，一次性整批入园，避免闸机识别错误</span></span></span><span style=\"color: #000000; font-size: 14px;\"><span style=\"font-weight: bold;\"><br /></span></span></p>\n<p style=\"margin: 0px 0px 1em; color: #333333; font-family: -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, 'Segoe UI', Arial, Roboto, 'PingFang SC', miui, 'Hiragino Sans GB', 'Microsoft Yahei', sans-serif; font-size: 16px; line-height: 1.5em;\">&nbsp;</p>\n<p style=\"margin: 0px 0px 1em; color: #333333; font-family: -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, 'Segoe UI', Arial, Roboto, 'PingFang SC', miui, 'Hiragino Sans GB', 'Microsoft Yahei', sans-serif; font-size: 16px; line-height: 1.5em;\"><span style=\"color: #000000; font-size: 14px;\"><strong><span style=\"font-family: 宋体;\">➢</span></strong><span style=\"font-weight: bold;\">注意事项：<br /></span>1、严禁携带易燃、易爆、危险品入场；禁止自行车、电瓶车、平衡车等进入；禁止高空抛物<br />2、高血压、心脏病 、恐高症和其它不适合高空活动疾病患者，严禁入内<br />3、挂榜岩&middot;竹尖漫步内有玻璃栈道，不建议穿高跟鞋体验</span></p>\n<p style=\"margin: 0px 0px 1em; color: #333333; font-family: -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, 'Segoe UI', Arial, Roboto, 'PingFang SC', miui, 'Hiragino Sans GB', 'Microsoft Yahei', sans-serif; font-size: 16px; line-height: 1.5em;\"><span style=\"color: #000000;\"><span style=\"font-size: 14px;\"><strong><span style=\"font-family: 宋体;\">➢</span></strong><span style=\"font-weight: bold;\">温馨提示：<br /></span>蜀南竹海景区门票政策、观光车、自驾详情，请咨询0831-8885199<br /></span><span style=\"font-weight: bold; font-size: 14px;\">挂榜岩&middot;竹尖漫步咨询热线：</span><span style=\"font-size: 14px;\">0831-4980779</span></span></p>",
        use_notice: '',
        withdrawal_notice:
          "<p><span style=\"font-family: -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, 'Segoe UI', Arial, Roboto, 'PingFang SC', miui, 'Hiragino Sans GB', 'Microsoft Yahei', sans-serif; font-size: 14px;\">在有效期内，未核销使用的，可联系客服申请退款，退款将原路返回至账户</span></p>",
        other_notice:
          "<div class=\"tee-view rule-label\" style=\"color: #323233; font-family: -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, 'Segoe UI', Arial, Roboto, 'PingFang SC', miui, 'Hiragino Sans GB', 'Microsoft Yahei', sans-serif; font-size: 14px; margin-bottom: 8px; line-height: 18px;\" data-v-838c9cc=\"\">其他说明</div>\n<div class=\"tee-view rule-list\" style=\"font-family: -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, 'Segoe UI', Arial, Roboto, 'PingFang SC', miui, 'Hiragino Sans GB', 'Microsoft Yahei', sans-serif; font-size: 14px; line-height: 18px; color: #969799; white-space: pre-wrap;\" data-v-838c9cc=\"\">1.景区所有的竹筏按定员载客，不得超载。 2.竹筏都是经景区管理部门审核通过的，有经营许可证，安全防护设施齐备。</div>",
        lowest_price: 1,
        total_sales_volume: 0,
        pictures: null,
        tags: [
          {
            id: 2,
            name: '当日可退',
            description: '',
          },
          {
            id: 3,
            name: '随买随用',
            description: '',
          },
          {
            id: 4,
            name: '电子门票',
            description: '',
          },
          {
            id: 6,
            name: '语音导览',
            description: '',
          },
          {
            id: 8,
            name: '7天无理由退改',
            description: '',
          },
          {
            id: 11,
            name: '测试',
            description: '测试打达到',
          },
          {
            id: 12,
            name: '身份证入园',
            description: '身份证入园',
          },
          {
            id: 13,
            name: '二维码入园',
            description: '二维码入园',
          },
        ],
        category: {
          id: 18,
          status: 'active',
          seq: 3,
          name: '蜀南竹海',
          description: 'test',
        },
        prices: [
          {
            date: '2023-06-08',
            price: 1,
          },
          {
            date: '2023-06-09',
            price: 1,
          },
          {
            date: '2023-06-10',
            price: 1,
          },
          {
            date: '2023-06-11',
            price: 1,
          },
        ],
        stocks: [
          {
            date: '2023-06-08',
            has_stock: true,
            sales_limit: 0,
            sales_volume: 1,
            value: '999999',
          },
          {
            date: '2023-06-09',
            has_stock: true,
            sales_limit: 0,
            sales_volume: 0,
            value: '999999',
          },
          {
            date: '2023-06-10',
            has_stock: true,
            sales_limit: 0,
            sales_volume: 0,
            value: '999999',
          },
          {
            date: '2023-06-11',
            has_stock: true,
            sales_limit: 0,
            sales_volume: 0,
            value: '999999',
          },
        ],
        batches: null,
        goodsGroup: {
          id: 0,
          name: null,
          status: 'deleted',
          purchase_strategy: null,
          description: null,
          create_time: null,
        },
        is_promissory_note: 1,
      },
    ],
    pageNum: 1,
    pageSize: 1,
    size: 1,
    startRow: 0,
    endRow: 0,
    pages: 1,
    prePage: 0,
    nextPage: 0,
    isFirstPage: true,
    isLastPage: true,
    hasPreviousPage: false,
    hasNextPage: false,
    navigatePages: 8,
    navigatepageNums: [1],
    navigateFirstPage: 1,
    navigateLastPage: 1,
  },
}
